### ISSUE TITLE
Support multiple types for "type"

### ISSUE THREAD

**Issue by endorama** [omissis/go-jsonschema#1]
Hello!

This project is awesome, but unfortunately seems to support only Draft 5 ( latest available is Draft 7 ). May I open a PR to update the Readme adding this information?

How do you plan to handle Draft releases in this project? Do you plan updating to the new Draft?

Thank you!

**Comment by atombender** [comment]
I haven't thought much about that, mostly because I don't have a clear idea about how the drafts process works and what people expect.

From what I can tell, there aren't [any changes](https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#appendix-B) between draft 5 and 7 that impact this project. (The generator completely ignores the `$schema` and won't warn if it's incompatible. I'd like to improve on that.) Do you know of any?

**Comment by atombender** [comment]
Right, this is actually in the readme:

https://github.com/atombender/go-jsonschema/blob/c7be101b983c8170a60c97e44c2efdb5da31df82/README.md#L78

Only a single type is supported at the moment.

This can be tricky to implement with Go, as you say, which doesn't have sum types. So if have something like `"type": ["string", "bool"]` we have two options: Use `interface{}`, or generate an interface which is something like:

```go
type StringOrBool interface {
  isStringOrBool()
}
type StringValue string
func (s StringValue) isStringOrBool()
type BoolValue bool
func (b boolValue) isStringOrBool()
```

and then you can check with a type switch. Using `interface{}` is easier to implement, but this makes the code-generation logic trickier, since we have to validate any value against both types. But doable.

If it's important to your use case I can see if I can implement it?

**Comment by endorama** [comment]
> Right, this is actually in the readme:

Sorry I missed that :(

> If it's important to your use case I can see if I can implement it?

Yes, it is, as I need multiple types. I could "work around" that, but that's really what I need.

I'm willing to contribute so please let me know if I can help!

**Comment by atombender** [comment]
I've given it a go. So far, limited validation, shouldn't be a problem. Let me know!
