### ISSUE TITLE
Enum integers are generated as floats. 

### ISSUE THREAD

**Issue by ksysoev** [omissis/go-jsonschema#102]
Hi.

I tried to update from version 0.8 to latest version and notice that enum integers are generated now as floats. It looks wrong to me. 

I found that the bug was introduces in this commit https://github.com/omissis/go-jsonschema/commit/d6bcd4e973a99306c5500f8d197da679a38de9c0#diff-e61a69b3198d366d9d9a553877eb95e92379b897c4b1417493e22a47dd8927f7L92-R94

it breaks generated code for unmarshaling, and lead to an error. 
```
invalid value (expected one of []interface {}{0, 1}): 1
```

**Comment by ksysoev** [comment]
@omissis I created [PR](https://github.com/omissis/go-jsonschema/pull/103), not sure it's the best place to handle this problem. I appreciate you guidance to make it mergeable.

**Comment by omissis** [comment]
hey @ksysoev , thanks for the pr. I am aware of that "weird" behaviour, as I was surprised by it myself when I had to implement it. If I recall correctly, that was due to the change in behaviour of a dependency that forced that kind of representation, but I need to look back at it as I honestly do not remember. Will keep you posted! :)

**Comment by ardrabczyk** [comment]
Hi @omissis,

are you going to merge the PR or fix this differently?

**Comment by omissis** [comment]
Hi, I haven't had time to look into the issue yet. Will do as soon as I can

**Comment by omissis** [comment]
Solved by #126 (which replaced #103)
