### ISSUE TITLE
Question about UnmarshalJSON on non-required fields

### ISSUE THREAD

**Issue by c0d3x42** [omissis/go-jsonschema#5]
with the following schema partial

```
  "type": "object",
  "properties": {
    "label": {
      "type": "string"
    }
  },
  "required": ["label"],
```
An `UnmarshalJSON()` is saved in the output file that will populate `Label` with the string from the JSON file.  Which looks like:
```
type MyThing struct {
	// Label corresponds to the JSON schema field "label".
	Label string `json:"label"`
}
```

When `required` is missing, so is the `UnmarshalJSON()` *and* the resulting output file has a `*string`, e.g.

```
type MyThing struct {
	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label"`
}
```

I've only started playing with golang today, so this may be a really obvious thing and my lack of understanding and familiarity with JSON marshalling is woefully incomplete.

But, wouldn't if be better if the `UnmarshallJSON()` was always created in the output and either
 * if field was optional
    * initialised it when it existed
 * if field was required
   * initialise it 
   * or errored if it didn't exist

I Hope that makes sense, once again, golang is all *very* new to me, any quite possibly its just a total lack of understanding of how to use pointers in go, and everything is doing what its supposed to.  So apologies if this is just a really dumb questions.

**Comment by atombender** [comment]
Not sure I understand what you mean. If the field is optional, we use a pointer (`*string`) because otherwise a missing string would be unmarshalled to an empty string. While Go developers sometimes use an empty string to mean "not present", but this is often not desirable, because that means it's not possible for your code to determine whether the original JSON had an empty string, a null string or a missing key.

Clearly string pointers are less convenient because you have to check whether they're nil, and you could accidentally write code they accessed the value without checking this first. But _semantically_ there's no way around it. (Maybe in the future we could have a flag to control this, though.)

Just to be clear, `UnmarshalJSON` _overrides_ the JSON decoder's built-in logic. We only generate it if we need to modify its behaviour or inject validation checks. If we don't, we don't generate it, and the normal JSON decoding will take place. In this case, the string field becomes either `nil` or a string -- it is initialized. 

Did I address your concern or did you mean something else?

**Comment by c0d3x42** [comment]
Thank you for detailed response. Yep, its all perfectly clear now. My issue was not understanding go and how pointers worked when `UnmarshalJSON` was called. My First foray into go was like stumbling in the dark.

**Comment by atombender** [comment]
Great!
